In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Users/DISCOVERY/Machine_Learning/Datasets/leukemia_dataset.csv")

In [3]:
df.head()

,1,2,3,4,5,6,7,8,9,10,...,7120,7121,7122,7123,7124,7125,7126,7127,7128,class
0,-1.187689,-1.335256,-0.797493,0.235632,-1.311206,-1.654381,-1.441690,-1.058556,-0.582683,0.001758,...,0.750758,-0.380081,0.526298,-0.888026,0.719203,0.419502,-0.487514,0.358999,-0.742858,0
1,-1.140946,-0.948874,0.330082,-0.147328,-1.447179,-1.883625,-0.162631,-1.273916,-0.073553,0.276874,...,1.373074,-0.909883,0.218674,-0.902198,0.973992,0.583725,-0.379892,0.276874,-0.813543,0
2,-1.318718,-1.385362,-1.185912,0.079371,-1.692895,-1.804723,-0.702679,-1.371271,-0.287485,0.304015,...,0.869148,-0.351883,0.721938,-0.912280,0.297393,0.424691,-0.631730,-0.357687,-0.906431,0
3,-1.148393,-1.460329,-0.873259,0.316744,-1.458799,-1.834167,0.245404,-1.257467,-0.281993,-0.271945,...,0.881785,-0.745177,0.666675,-0.925688,0.982218,0.652906,-0.392963,0.284555,-0.835275,0
4,-1.133227,-1.250520,-0.779262,-0.035696,-1.169730,-1.776766,-1.021123,-1.452207,0.022153,-1.089860,...,0.745409,-0.701555,0.647910,-0.744249,0.885682,0.531352,-0.591456,0.117886,-0.516429,1

In [4]:
df.shape

(72, 7129)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 7129 entries, 1 to class
dtypes: float64(7128), int64(1)
memory usage: 3.9 MB

In [8]:
df.isna().mean()

1        0.0
2        0.0
3        0.0
4        0.0
5        0.0
        ...
7125     0.0
7126     0.0
7127     0.0
7128     0.0
class    0.0
Length: 7129, dtype: float64

In [9]:
df.describe()

,1,2,3,4,5,6,7,8,9,10,...,7120,7121,7122,7123,7124,7125,7126,7127,7128,class
count,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,...,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000
mean,-1.019260,-1.175825,-0.594848,0.140395,-1.401175,-1.677901,-0.759348,-1.254986,-0.228559,-0.281025,...,0.877972,-0.584006,0.448531,-0.721063,0.939138,0.349984,-0.512853,0.360993,-0.714875,0.347222
std,0.294946,0.242111,0.488385,0.307690,0.264941,0.156681,0.811607,0.192918,0.358923,0.726178,...,0.272580,0.348409,0.413117,0.233204,0.354898,0.349302,0.195686,0.571534,0.198897,0.479428
min,-1.671903,-1.681944,-1.422571,-0.697961,-1.837961,-2.009669,-2.335874,-1.595796,-1.205313,-1.854389,...,-0.083958,-1.369024,-0.868378,-1.465454,-0.218494,-0.657700,-1.245923,-1.022012,-1.204950,0.000000
25%,-1.198886,-1.335256,-0.944131,-0.051160,-1.545701,-1.776980,-1.442937,-1.383986,-0.548834,-0.951175,...,0.724077,-0.818792,0.224891,-0.894901,0.751950,0.167578,-0.606557,0.074436,-0.826214,0.000000
50%,-1.052420,-1.194307,-0.618057,0.231388,-1.446678,-1.701803,-0.963427,-1.267413,-0.226964,-0.088548,...,0.899308,-0.582789,0.469184,-0.719583,0.967675,0.381216,-0.487217,0.233554,-0.722513,0.000000
75%,-0.857292,-1.052904,-0.312911,0.358999,-1.300586,-1.593297,-0.061351,-1.146612,0.070909,0.283796,...,1.038075,-0.280851,0.632720,-0.552732,1.138303,0.598073,-0.415145,0.509845,-0.606200,1.000000
max,-0.106917,-0.563622,0.646610,0.636459,0.133302,-1.046624,0.842022,-0.567541,0.468790,1.000321,...,1.373074,0.193353,1.707818,-0.262653,1.519528,1.000031,-0.052590,1.771676,-0.064213,1.000000

In [12]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
x = df.iloc[:,0:7127]
y = df.iloc[:,-1]

In [13]:
#applying the SelectBest class to extract the top 40 best features
bestfeatures = SelectKBest(score_func=f_classif, k=40)
fit = bestfeatures.fit(x,y)

In [14]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

In [15]:
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Feature', 'Score']

In [16]:
featureScores

     Feature      Score
0          1   3.771637
1          2   0.007126
2          3   0.505713
3          4   3.465958
4          5   0.055531
...      ...        ...
7122    7123   0.140869
7123    7124   0.257015
7124    7125   0.000212
7125    7126   0.720550
7126    7127  10.162161

[7127 rows x 2 columns]

In [18]:
print(featureScores.nlargest(40, 'Score')) #outputs the best 40 features

     Feature       Score
3251    3252  182.955666
2287    2288  167.820172
1833    1834  165.512712
6853    6854  150.323539
759      760  117.816410
1881    1882  117.579799
803      804  115.768997
2353    2354   98.063295
5500    5501   90.162416
1143    1144   86.649463
2120    2121   86.369787
1684    1685   83.889693
1744    1745   80.831160
4327    4328   80.819932
4210    4211   80.789756
6040    6041   79.901877
4846    4847   77.390356
6280    6281   74.399901
4372    4373   72.021771
6377    6378   68.072909
2127    2128   67.600197
2641    2642   65.900294
4376    4377   65.407282
1629    1630   63.882506
2019    2020   62.253377
1778    1779   61.503300
4972    4973   60.834094
5771    5772   60.428451
757      758   58.538620
4290    4291   58.448152
1908    1909   57.429766
7117    7118   57.062056
4106    4107   56.904101
4166    4167   56.543984
6375    6376   56.281384
1927    1928   55.620943
1259    1260   55.275615
5086    5087   54.894260
1952    1953   54.621045
2440    2441   54.211987